# Generated by Django 3.1 on 2022-04-15 05:51

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shiftan.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, max_length=50, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email_address')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_manager', models.BooleanField(default=False, verbose_name='manager')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_name', models.CharField(max_length=50, verbose_name='名字')),
                ('first_name', models.CharField(max_length=50, verbose_name='名前')),
                ('phone', models.CharField(max_length=15, verbose_name='電話番号')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', shiftan.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Shift_Range',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=100, verbose_name='シフト名')),
                ('start_date', models.DateField(verbose_name='募集開始日')),
                ('stop_date', models.DateField(verbose_name='募集終了日')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='シフト作成時間')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='シフト更新時間')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100, unique=True, verbose_name='店舗名')),
                ('address', models.CharField(max_length=100, verbose_name='住所')),
                ('phone', models.CharField(max_length=15, verbose_name='電話番号')),
                ('store_ID', models.SlugField(unique=True, verbose_name='店舗ID')),
            ],
        ),
        migrations.CreateModel(
            name='Work_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='バイト開始時間')),
                ('stop_time', models.DateTimeField(verbose_name='バイト終了時間')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='シフト希望提出時間')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='シフト希望更新時間')),
                ('shift_range_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftan.shift_range')),
                ('user_FK', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tmp_Work_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='シフト希望開始時間')),
                ('stop_time', models.DateTimeField(verbose_name='シフト希望終了時間')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='シフト希望提出時間')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='シフト希望更新時間')),
                ('shift_range_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftan.shift_range')),
                ('user_FK', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule_Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='シフトテンプレ開始時間')),
                ('stop_time', models.DateTimeField(verbose_name='シフトテンプレ終了時間')),
                ('user_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, verbose_name='グループ名')),
                ('color', models.SlugField(max_length=100, verbose_name='グループカラー')),
                ('Store_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftan.store')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='group_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shiftan.group'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='store_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shiftan.store'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
