# Generated by Django 3.2.10 on 2022-04-29 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shiftan', '0003_alter_group_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'グループ', 'verbose_name_plural': 'グループ'},
        ),
        migrations.AlterModelOptions(
            name='schedule_template',
            options={'verbose_name': 'シフトテンプレ', 'verbose_name_plural': 'シフトテンプレ'},
        ),
        migrations.AlterModelOptions(
            name='shift_range',
            options={'verbose_name': 'シフト範囲', 'verbose_name_plural': 'シフト範囲'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': '店舗', 'verbose_name_plural': '店舗'},
        ),
        migrations.AlterModelOptions(
            name='tmp_work_schedule',
            options={'verbose_name': 'シフト希望', 'verbose_name_plural': 'シフト希望'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'ユーザー', 'verbose_name_plural': 'ユーザー'},
        ),
        migrations.AlterModelOptions(
            name='work_schedule',
            options={'verbose_name': '作成シフト', 'verbose_name_plural': '作成シフト'},
        ),
        migrations.AddField(
            model_name='shift_range',
            name='store_FK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shiftan.store'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work_schedule',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='シフト作成時間'),
        ),
        migrations.AlterField(
            model_name='work_schedule',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='シフト更新時間'),
        ),
        migrations.AlterModelTable(
            name='group',
            table='group',
        ),
        migrations.AlterModelTable(
            name='schedule_template',
            table='schedule_template',
        ),
        migrations.AlterModelTable(
            name='shift_range',
            table='shift_range',
        ),
        migrations.AlterModelTable(
            name='store',
            table='store',
        ),
        migrations.AlterModelTable(
            name='tmp_work_schedule',
            table='tmp_work_schedule',
        ),
        migrations.AlterModelTable(
            name='work_schedule',
            table='work_schedule',
        ),
    ]
