# Generated by Django 3.2.10 on 2022-04-29 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiftan', '0004_auto_20220429_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='Store_FK',
            new_name='store_FK',
        ),
    ]
